version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get -v ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v
          working_directory: ./test/
      - run:
          name: Build and push Docker image
          command: |
            docker build -t demo/userservice:1.0 .
            echo $dockerhubpass | docker login -u $DOCKER_LOGIN --password-stdin
            docker push demo/userservice:1.0