version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get -v ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v
          working_directory: ./test/

      - setup_remote_docker:
          version: 19.03.13

      - run:
          name: Build and push Docker image
          command: docker build -t rushikeshnere/demo:1.0 . && docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD  &&  docker push rushikeshnere/demo:1.0